# Create the conda environment
name: gravmag-env
channels:
    - conda-forge
dependencies:
    - numpy
    - scipy
    - xarray
    - pandas
    - geopandas
    - shapely
    - matplotlib
    - vedo
    - jupyterlab
    - streamlit
    - black
    - pytest
    - pytest-cov
    - pip