import numpy as np
from .. import check, utils, data_structures
from .. import constants as cts
from .. import inverse_distance as idist

def grav(coordinates, lines, density, field, scale=True):
    """
    Gravitational z derivative produced by vertical lines in Cartesian coordinates.
    All values are referred to a topocentric Cartesian system with axes
    x, y and z pointing to north, east and down, respectively.

    Parameters
    ----------
    coordinates : dictionary
        Dictionary containing the x, y and z coordinates at the keys 'x', 'y' and 'z',
        respectively. Each key is a numpy array 1d having the same number of elements.
        All coordinates should be in meters.
    lines : dictionary
        Dictionary containing the x, y, z1 (top) and z2 (bottom) coordinates of each line in lines.
        Each key is a numpy array 1d having the same number of elements.
    density : 1d-array
        1d-array containing the density of each prism in kg / m.
    field : str
        Gravitational field to be computed.
        The available fields are:
        - z-component of acceleration: ``z`` (in mGal)
     scale : boolean
        Defines if the resultant field will be multiplied by scale factors
        "constants.GRAVITATIONAL_CONST" (Gravitational constant) and
        "constants.SI2MGAL" (constant tranforming from m / s² to mGal).

    Returns
    -------
    result : array
        Gravitational field generated by the lines at the computation points.

    """

    # Verify the input parameters
    D = check.are_coordinates(coordinates)  # D = total number of data points
    P = check.are_vertical_lines(lines)  # P = total number of prisms
    check.is_array(density, ndim=1, shape=(P,))

    # Verify the field
    if field not in kernels:
        raise ValueError("Gravitational field {} not recognized".format(field))

    # compute the contribution of each vertex
    result = iterate_over_vertices(coordinates, lines, density, kernels[field])

    # multiply the computed field by the corresponding scale factors
    if scale is True:
        result *= cts.GRAVITATIONAL_CONST
        # Convert from m/s^2 to mGal
        if field in ["x", "y", "z"]:
            result *= cts.SI2miliGAL
        # Convert from 1/s^2 to Eötvös
        if field in ["xx", "xy", "xz", "yy", "yz", "zz"]:
            result *= cts.SI2EOTVOS

    return result

# iterate over vertices
def iterate_over_vertices(coordinates, lines, sigma, kernel):
    """
    Function for iterating over the vertices of the vertical lines
    by using numpy with broadcasting
    """
    predicted_field = np.zeros(
        (coordinates["x"].size, lines["x"].size), dtype="float"
    )
    # horizontal coordinates
    X = (
        -coordinates["x"][:, np.newaxis]
        + lines["x"][np.newaxis, :]
    )
    Y = (
        -coordinates["y"][:, np.newaxis]
        + lines["y"][np.newaxis, :]
    )
    # contribution of vertices z1
    # Squared Euclidean Distance Matrix (SEDM)
    R2 = idist.sedm(
        data_points=coordinates,
        source_points={
            "x": lines["x"],
            "y": lines["y"],
            "z": lines["z1"],
        },
        check_input=False,
    )
    # vertical coordinate
    Z = (
        -coordinates["z"][:, np.newaxis]
        + lines["z1"][np.newaxis, :]
    )
    predicted_field[:] -= kernel(X, Y, Z, np.sqrt(R2))

    # contribution of vertices z2
    R2 += idist.sedm_delta_z(
        data_points=coordinates,
        source_points={
            "x": lines["x"],
            "y": lines["y"],
            "z": lines["z1"],
        },
        delta_z = lines["z2"] - lines["z1"],
        check_input=False,
    )
    Z += (
        -coordinates["z"][:, np.newaxis]
        + (lines["z2"] - lines["z1"])[np.newaxis, :]
    )
    predicted_field[:] += kernel(X, Y, Z, np.sqrt(R2))

    predicted_field = np.sum(a=predicted_field * sigma[np.newaxis, :], axis=1)

    return predicted_field

# kernels
def kernel_z(X, Y, Z, R):
    """
    Function for computing the z-derivative of inverse distance kernel
    for a vertical line
    """
    result = -(
        Y * utils.safe_log(X + R)
        + X * utils.safe_log(Y + R)
        - Z * utils.safe_atan2(Y * X, Z * R)
    )
    return result

# Available kernels
kernels = {
    "z": kernel_z,
}